cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_content, name='cart_content'),
    re_path(r'^(?P<id>\d+)/add$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^(?P<id>\d+)/remove$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^(?P<id>\d+)/edit$', views.edit_cart, name='edit_cart'),
    re_path(r'clearall/', views.clear_all, name='clear_all'),
    re_path(r'^(?P<id>\d+)/update_quantity$', views.update_quantity, name='update_quantity')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/auth/', include('shop_auth.urls')),
    path('shop/auth/', include('django.contrib.auth.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class CartForm(forms.Form):

    quantity = forms.IntegerField(min_value=1)
    update = forms.BooleanField(initial=False, required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse, HttpResponse
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from cart.forms import CartForm
from django.conf import settings

# Create your views here.

@require_POST
def add_to_cart(request, id):
    product = get_object_or_404(Product, id=id)
    cart = Cart(request)
    cart_form = CartForm(request.POST)
    if cart_form.is_valid():
        data = cart_form.cleaned_data
        cart.add(product=product, quantity=data['quantity'])
        return redirect(product.get_absolute_url())



def remove_from_cart(request, id):
    product = get_object_or_404(Product, id=id)
    cart = Cart(request)
    cart.remove(product)

    return redirect('cart:cart_content')

def cart_content(request):
    cart_content = Cart(request)
    cart_content = cart_content.get_cart_content()
    total_price = 0

    if cart_content:
        for product in cart_content:
            total_price += float(product['total_price'])

    context = {
        'cart_content': cart_content,
        'total_price': round(total_price, 2)
    }

    return render(request, 'cart/content.html', context)

def edit_cart(request, id):
    instance = get_object_or_404(Product, id=id)
    cart_form = CartForm()
    context = {
        'instance': instance,
        'cart_form': cart_form
    }

    return render(request, 'cart/edit_cart.html', context)

def update_quantity(request, id):
    product = get_object_or_404(Product, id=id)
    cart = Cart(request)
    quantity = request.POST.get("quantity")

    cart.update_quantity(product, quantity=quantity)

    return redirect('cart:cart_content')


def clear_all(request):
    cart = Cart(request)
    cart.clear_all()
    return redirect('cart:cart_content')

cart/templates/cart/content.html
{% extends "shop/base.html" %}

{% block content %}
<div class="mt-3"></div>
<h1 class="text-center">Your Cart Content</h1>
<div class="table-responsive">
<table class="table table-dark">
<thead>
  <tr>
    <th scope="col">Product Name</th>
    <th scope="col">Price</th>
    <th scope="col">Quantity</th>
    <th scope="col">Action</th>
  </tr>
</thead>
<tbody>
  {% if cart_content %}
  {% for product in cart_content %}
    <tr>
      <td>{{ product.product_name }}</td>
      <td>${{ product.price }}</td>
      <td>
        <form class="qform" action="{% url 'cart:update_quantity' product.product_id %}" method="post">
          {% csrf_token %}
          <input type="number" name="quantity" class="q-number" min="1" value="{{ product.quantity }}">
        </form>
      </td>
      <td>
        <a href="{% url 'cart:remove_from_cart' product.product_id %}" class="btn btn-danger">Remove</a>
      </td>
    </tr>
  {% endfor %}
  {% else %}
  <tr>
    <td>Nothing in cart</td>
  </tr>
  {% endif %}

</tbody>
</table>
</div>


<div class="cart-actions float-right">
  <span class="total-price"><h3>Total Price: ${{ total_price }}</</h3><span>
    <form class="d-inline" action="{% url 'cart:clear_all' %}" method="post">
      {% csrf_token %}
      <button type="submit" name="button" class="btn btn-danger">Clear All</button>
    </form>
  <span class="pl-2"></span>
  <button type="button" name="button" class="btn btn-primary">Checkout</button>
</div>

{% endblock %}