shop_auth/urls.py
from django.urls import re_path
from . import views

app_name = 'shop_auth'

urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate_user, name='activate'),
    re_path(r'^message/$', views.confirm_message, name='confirm_message'),
    re_path(r'^activated/$', views.activation_success, name='activation_success'),
    re_path(r'^request_activation/$', views.request_activation, name='request_activation')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/auth/', include('shop_auth.urls')),
    path('shop/auth/', include('django.contrib.auth.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_countries.fields import CountryField

# Create your models here.

class CustomUser(AbstractUser):
    country = CountryField(blank_label='(select country)')
    address = models.TextField()
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.username

shop_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django_countries.fields import CountryField
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2', 'country', 'address')

class RequestActivationLinkForm(forms.Form):
    username = forms.CharField(label='Username')

shop_auth/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
from .forms import CustomUserCreationForm, RequestActivationLinkForm
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth import login, authenticate
from django.core.mail import EmailMessage
from .models import CustomUser

# Needed Functions.
def send_activation_link(request, user, to_email):
    # Begin Activation Link Logic Proccess.
    current_site = get_current_site(request)
    mail_subject = 'Shppy Activation'
    message = render_to_string('shop_auth/acc_active_email.html', {
        'user': user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
        'token':account_activation_token.make_token(user)
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    email.send()

# Create your views here.

def register(request):

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            to_email = form.cleaned_data.get('email')
            send_activation_link(request, user,to_email)
            return redirect('shop_auth:confirm_message')
        else:
            return render(request, 'shop_auth/register.html', {'form':form, 'title':'register'})


    form = CustomUserCreationForm()
    context = {
        'title': 'Register',
        'form': form,
    }

    return render(request, 'shop_auth/register.html', context)

def activate_user(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.active = True
        user.save()
        return redirect('shop_auth:activation_success')
    else:
        return HttpResponse('Activation link is invalid!')

def confirm_message(request):
    return render(request, 'shop_auth/confirmation_message_page.html', context=None)

def activation_success(request):
    return render(request, 'shop_auth/confirmation_success.html', context=None)

def request_activation(request):
    if request.method == 'POST':
        form = RequestActivationLinkForm(request.POST)
        if form.is_valid():
            user = get_object_or_404(CustomUser, username=request.user.username)
            print(user)
            return HttpResponse('0')
    user = get_object_or_404(CustomUser, username=request.user.username)
    send_activation_link(request, user, user.email)
    return redirect('shop_auth:confirm_message')

shop_auth/templates/shop_auth/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'shop_auth:activate' uidb64=uid token=token %}
{% endautoescape %}

shop_auth/templates/shop_auth/confirmation_message_page.html
{% extends "shop/base.html" %}

{% block content %}
<p>Please check your email to confirm your registration.</p>
{% endblock content %}

shop_auth/templates/shop_auth/confirmation_success.html
{% extends "shop/base.html" %}

{% block content %}
{% if request.user.is_authenticated %}
    <h1>Your Account is Activated Now</h1>
{% else %}
    <h1>Your Account is Activated Now</h1>
    <p>You may <a href="{% url 'login' %}">login</a></p>
{% endif %}

{% endblock content %}

shop_auth/templates/shop_auth/register.html
{% extends "shop/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="row register-form">
<div class='col-md-7 d-flex justify-content-center'>
    <h1 class='text-center'>Register</h1>

        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
</div>
<div class='col-md-5'>
    <form action="{% url 'shop_auth:register' %}" method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <button type='submit' class='btn btn-primary'>Register</button>
    <div class="mb-3"></div>
    </form>
</div>
</div>

{% endblock content %}

shop_auth/templates/shop_auth/request_activation.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h3>please type your username to send you the activation link.</h3>
    <div class="row">
        <div class="col-sm-12 col-md-4 offset-md-4">
            <form action="{% url 'shop_auth:request_activation' %}" method='post'>
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class='btn btn-primary'>Send Link</button>
            </form>
        </div>
    </div>
{% endblock content %}