cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_content, name='cart_content'),
    re_path(r'^(?P<id>\d+)/add$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^(?P<id>\d+)/remove$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^(?P<id>\d+)/edit$', views.edit_cart, name='edit_cart'),
    re_path(r'clearall/', views.clear_all, name='clear_all'),
    re_path(r'^(?P<id>\d+)/update_quantity$', views.update_quantity, name='update_quantity')
]

shop/urls.py
from django.urls import re_path
from . import views

app_name = 'shop'

urlpatterns = [
    re_path(r'^profile/$', views.get_profile, name='get_profile'),
    re_path(r'^$', views.list_products, name='list_products'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.list_products, name='list_product_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/auth/', include('shop_auth.urls')),
    path('shop/auth/', include('django.contrib.auth.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wishlist/urls.py
from django.urls import re_path
from . import views

app_name = 'wishlist'

urlpatterns = [
    re_path(r'^$', views.wishlist, name='list_wishlist_products'),
    re_path(r'^wishlist/add$', views.add_to_wishlist, name='add_to_wishlist'),
    re_path(r'^(?P<id>\d+)/wishlist/remove$', views.remove_from_wishlist, name='remove_from_wishlist'),
    re_path(r'^clear/$', views.clear_all, name='clear_all')
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.

class Category(models.Model):

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ("name", )
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:list_product_category', args=[self.slug])


class Product(models.Model):

    category    = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name        = models.CharField(max_length=200, db_index=True)
    slug        = models.SlugField(max_length=200, db_index=True)
    Image       = models.ImageField(upload_to='product_images', default='product_images/default.jpg')
    description = models.TextField(blank=True)
    price       = models.DecimalField(max_digits=10, decimal_places=2)
    stock       = models.PositiveIntegerField()
    available   = models.BooleanField(default=True)
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', )
        index_together = (('id', 'slug'), )
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
    
    def get_image_url(self):
        return self.Image.url

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartForm
from wishlist.forms import WishlistForm
from wishlist.wishlist import Wishlist
from django.conf import settings
from shop_auth.models import CustomUser
# Create your views here.

def list_products(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug == 'all':
        category = 'all'

    if category_slug and category_slug != 'all':
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }

    return render(request, 'shop/product/list.html', context)

def product_detail(request, id, slug=None):
    cart_form = CartForm()
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    wishlist = Wishlist(request)

    if not slug:
        cart_form = CartForm(instance=product)

    # Check if the product is in wishlist otherwise set the wishlist form to None.
    if str(id) in wishlist.get_wishlist_session_content():
        wishlist_form = None
    else:
        wishlist_form = WishlistForm({'product_id': id})

    context = {
        'product': product,
        'cart_form': cart_form,
        'wishlist_form': wishlist_form
    }

    return render(request, 'shop/product/details.html', context)

def get_profile(request):
    user = get_object_or_404(CustomUser, username=request.user.username)
    context = {
        'active': user.active
    }
    return render(request, 'shop/user/profile.html', context)

shop/templates/shop/product/details.html
{% extends "shop/base.html" %}
{% load static %}
{% block title_ %}
  {{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <img src="{{ product.Image.url }}" class="img-fluid img-thumbnail" alt="product image">
    </div>
    <div class="col-sm-12 col-md-6">
      <h1>{{ product.name }}</h1>
      <p>category: <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></p>
      <p>Price: ${{ product.price }}</p>
      {{ product.description | linebreaks }}

      <form class="" action="{% url 'cart:add_to_cart' id=product.id %}" method="post">
            {% csrf_token %}
            {{ cart_form }}
            <button type="submit" name="button" class="btn btn-primary">Add</button>
      </form>

     
      {% if wishlist_form %}  <!-- Check if it is in wishlist -->
        <form action="{% url 'wishlist:add_to_wishlist' %}" method='post'>
          {% csrf_token %}
          {{ wishlist_form }}
          <button type='submit' class="btn">Add To Wishlist <img src="{% static "img/heart.png" %}" width=20 alt="heart"> </button>
        </form>
      {% else %}
        <button class='btn' disabled>Added to wishlist</button>
      {% endif %}
      
    </div>
  </div>
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}

{% block title_ %}
    {% if category %}
      {{ category.name }}
      {% else %}
        Products
    {% endif %}
{% endblock %}

{% block content %}
<div class="list-wrapper">
  <div class="row">
    <div class="side-bar col-sm-12 col-md-3">
      <h3>Categories</h3>
        <ul class="nav flex-column">
          <li class="nav-item
          {% if category == 'all' %}
              active
          {% endif %}
          ">
            <a class="nav-link" href="{% url 'shop:list_product_category' category_slug='all' %}">All</a>
          </li>

          {% for cat in categories %}
            <li class="nav-item
            {% if category.slug == cat.slug %}
              active
            {% endif %}
            ">
              <a class="nav-link" href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
            </li>
          {% endfor %}
        </ul>
      </ul>
    </div>
    <div class="mt-2 d-sm-block d-md-none"> <br> </div>
    <div class="main-content col-sm-12 col-md-9">
        <div class="row">
          {% if products %}
            {% for prod in products  %}
            <div class="col-sm-12 col-md-4">
              <div class="card">
                <img class="card-img-top" src="{{ prod.Image.url }}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title"> <a href="{{ prod.get_absolute_url }}">{{ prod.name }}</a> </h5>
                    <span class="price">Price: ${{ prod.price }}</span>
                  </div>
                </div>
            </div>
            <div class="mt-2 d-sm-block d-md-none"> <br> </div>
            {% endfor %}
            {% else %}
            No products in stock
          {% endif %}
        </div>
    </div>
  </div>
</div>
{% endblock %}