cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_content, name='cart_content'),
    re_path(r'^(?P<id>\d+)/add$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^(?P<id>\d+)/remove$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^(?P<id>\d+)/edit$', views.edit_cart, name='edit_cart'),
    re_path(r'clearall/', views.clear_all, name='clear_all'),
    re_path(r'^(?P<id>\d+)/update_quantity$', views.update_quantity, name='update_quantity')
]

shop/urls.py
from django.urls import re_path
from . import views

app_name = 'shop'

urlpatterns = [
    re_path(r'^profile/$', views.get_profile, name='get_profile'),
    re_path(r'^$', views.list_products, name='list_products'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.list_products, name='list_product_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop_auth/urls.py
from django.urls import re_path
from . import views

app_name = 'shop_auth'

urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate_user, name='activate'),
    re_path(r'^message/$', views.confirm_message, name='confirm_message'),
    re_path(r'^activated/$', views.activation_success, name='activation_success'),
    re_path(r'^request_activation/$', views.request_activation, name='request_activation')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/auth/', include('shop_auth.urls')),
    path('shop/auth/', include('django.contrib.auth.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wishlist/urls.py
from django.urls import re_path
from . import views

app_name = 'wishlist'

urlpatterns = [
    re_path(r'^$', views.wishlist, name='list_wishlist_products'),
    re_path(r'^wishlist/add$', views.add_to_wishlist, name='add_to_wishlist'),
    re_path(r'^(?P<id>\d+)/wishlist/remove$', views.remove_from_wishlist, name='remove_from_wishlist'),
    re_path(r'^clear/$', views.clear_all, name='clear_all')
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.

class Category(models.Model):

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ("name", )
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:list_product_category', args=[self.slug])


class Product(models.Model):

    category    = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name        = models.CharField(max_length=200, db_index=True)
    slug        = models.SlugField(max_length=200, db_index=True)
    Image       = models.ImageField(upload_to='product_images', default='product_images/default.jpg')
    description = models.TextField(blank=True)
    price       = models.DecimalField(max_digits=10, decimal_places=2)
    stock       = models.PositiveIntegerField()
    available   = models.BooleanField(default=True)
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', )
        index_together = (('id', 'slug'), )
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
    
    def get_image_url(self):
        return self.Image.url

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartForm
from wishlist.forms import WishlistForm
from wishlist.wishlist import Wishlist
from django.conf import settings
from shop_auth.models import CustomUser
# Create your views here.

def list_products(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug == 'all':
        category = 'all'

    if category_slug and category_slug != 'all':
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }

    return render(request, 'shop/product/list.html', context)

def product_detail(request, id, slug=None):
    cart_form = CartForm()
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    wishlist = Wishlist(request)

    if not slug:
        cart_form = CartForm(instance=product)

    # Check if the product is in wishlist otherwise set the wishlist form to None.
    if str(id) in wishlist.get_wishlist_session_content():
        wishlist_form = None
    else:
        wishlist_form = WishlistForm({'product_id': id})

    context = {
        'product': product,
        'cart_form': cart_form,
        'wishlist_form': wishlist_form
    }

    return render(request, 'shop/product/details.html', context)

def get_profile(request):
    user = get_object_or_404(CustomUser, username=request.user.username)
    context = {
        'active': user.active
    }
    return render(request, 'shop/user/profile.html', context)

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title_ %}
        Home
      {% endblock %}
    </title>
  </head>
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
  <body class="bg-light">
    <div class="container main bg-white">
      <header class="">
        <a href="{% url 'shop:list_products' %}" class='text-center text-dark'> <h3>Shppy</h3></a>
        <ul class="nav nav-pills nav-fill">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'list_products' %} active {% endif %}" href="{% url 'shop:list_products' %}">Home</a>
          </li>
          <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link {% if request.resolver_match.url_name == 'register' %} active {% endif %}" href="{% url 'shop:get_profile' %}">Profile</a>
          {% else %}
            <a class="nav-link {% if request.resolver_match.url_name == 'register' %} active {% endif %}" href="{% url 'shop_auth:register' %}">Sign Up</a>
          {% endif %}
            
          </li>
          <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Log out</a>
          {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          {% endif %}
          </li>
          
      </ul>

      <div class='navbar'>
          <ul class="navbar-nav flex-row justify-content-center justify-content-md-end w-100">
          {% if user.is_authenticated %}
            <li class="nav-item p-3">
              <span>Hi {{ user.username }}</span>
            </li>
          {% endif %}
            <li class="nav-item p-3">
              <div class="wishlist"> <a href="{% url 'wishlist:list_wishlist_products' %}"> Wishlist<img src="{% static "img/heart.png" %}" class="img-fluid ml-2" width='20' alt="cart img"> </a> </div>
            </li>
            <span class='p-3'>|</span>
            <li class="nav-item mr-2 p-3">
              <div class="cart"> <a href="{% url 'cart:cart_content' %}"> <img src="{% static "img/cart.png" %}" class="img-fluid cart-img" alt="cart img"> </a> </div>
            </li>
          </ul>
        </div>
      </header>

      {% block content %}{% endblock %}
    </div>
    <script src="{% static "js/jquery.js" %}" charset="utf-8"></script>
    <script src="{% static "js/bootstrap.min.js" %}" charset="utf-8"></script>
    <script src="{% static "js/plugins.js" %}" charset="utf-8"></script>
  </body>
</html>